DELETE http://localhost:3003/api/blogs/62c686d1f6044e930b0a10a2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1a1BlayIsImlkIjoiNjJjNTg4Yzc1Njg3MmNhZmYwZGIxYzgxIiwiaWF0IjoxNjU3MTc3OTE5fQ.d6IClReVRmw_MOsYzx2D14vi5b-kaNLrqKksqviZG_8

{
  "title": "Kettu blog",
  "author": "Aku Tuhkanen",
  "url": "http://blog.orava.fi",
  "likes": 55
}